ALTER TABLE assets ADD COLUMN filename TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN source_created_at TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN source_modified_at TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN imported_at TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN metadata_json TEXT NOT NULL DEFAULT '{}';
